[tool.poetry]
name = "al25"
version = "1.0.1"
description = "Python Poetry Environment for Autonomous Learning course in 2025 from INS, CAU Kiel"
authors = ["Nikita Smirnov <nsm@informatik.uni-kiel.de>", "Connor Schönberner <cos@informatik.uni-kiel.de>"]

[tool.poetry.dependencies]
python = "^3.13"
protobuf = "3.20.0"
pysc2 = { git = "https://github.com/ConnorObrian/pysc2.git" }
numpy = "*"
pandas = "*"
gym = "^0.26.0"
gymnasium = "*"
scikit-learn = "*"
seaborn = "*"
matplotlib = "*"
standard-imghdr = "*"
tensorboard = "*"
torch-tb-profiler = "*"
absl-py = "*"
torch = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
package-mode = false